- name: "XII: Inner Demons"
  patreontier: Cyber Familiar
  image: /img/xii_inner_demons.png
  description: |
    You have become the target of a monstrosity beyond human reckoning. An otherworldly monster known as an Archdemon, which has pulled you into a surreal and nightmarish world of magic and mystery.
    
    <br/>
    It has weaponized your fears, manifested your darkest terrors into the world around you, and now waits for twelve days to pass, at the end of which it will break into the world and devour you whole.
    <br/>
    But you are not alone. With others pulled into the wake of the Archdemon and your own cadre of lesser demons willing to fight alongside you to save their own skin, you’ll have to call on every last drop of your will and your courage to survive.
    <br/>
    You have twelve days. Will you manage to stop the clock?
- name: "Violet Tangerine"
  status: ALPHA
  image: /img/violet_tangerine.png
  patreontier: Mechapprentice
  patreonexclusive: true
  description: |
    Violet Tangerine is a roleplaying game about the 2e edition of the Italian Job TTRPG, a more streamlined version of the original TTRPG from the 60s; it is lost media, found only reprinted in the last pages of d20 Italian Job released under the OGL in 2003.

    <br/>It is also a game about heists. The tempo of a heist, the gathering of a Crew, the montage of a plan coming together and when everything falls apart.

    <br/>In this game you gather a crew of talented and determined individuals and have them try to beat a heist-like scenario. One of you will play the opposition, the House protecting its prizes. Every action counts, so plan carefully and try to squeeze as many advantages for later, but beware, ‌the House creates new threats as your options decrease.

    <br/>Can you make it to the end of the scenario and escape with a big payout?
- name: "HEAT"
  status: ALPHA
  image: /img/heat.webp
  patreontier: Hex Processor
  patreonexclusive: true
  description: |
    HEAT - short for High Excitement Action Tabletop - is built on an extremely simple, fast resolution mechanic that is able to then create a completely unexpected outcome, despite the fact it uses no dice or randomness at all. It recreates the tension and thrilling action of a fast paced video game or bone breaking action movie with just a few simple mechanics that unfold into greater and greater complexity as you apply yourself to the game.